### ISSUE TITLE
installing local-tld via npm as sudo gives errors 

### ISSUE THREAD

**Issue by nborwankar** [hoodiehq-archive/local-tld#10]
- sudo npm install -g local-tld  or npm install -g local-tld

ends up in a prompt that asks for my sudo passwd but doesn't recognize it.  

All other sudo commands work and my passwd works on those 
- just as an A/B test I tried 
  sudo npm install -g request
  that works

Even when I have just used sudo a few seconds before on another command which worked I still get asked for my passwd and it fails.

 i.e. the issue is not with my passwd it seems to be with the local-tld install script.

==== long - see transcript below

``` shell
npm install -g local-tld
npm http GET https://registry.npmjs.org/local-tld
npm http 304 https://registry.npmjs.org/local-tld

> local-tld@3.0.2 preuninstall /usr/local/lib/node_modules/local-tld
> ./bin/local-tld-uninstall

+ sudo launchctl unload /Library/LaunchDaemons/ie.hood.local-tld-firewall.plist
Password:
+ launchctl unload /Users/nitin/Library/LaunchAgents/ie.hood.local-tld-service.plist
+ sudo rm -f /Library/LaunchDaemons/ie.hood.local-tld-firewall.plist
+ rm -f /Users/nitin/Library/LaunchAgents/ie.hood.local-tld-service.plist
+ sudo rm -f /etc/resolver/dev

> local-tld@3.0.2 preuninstall /usr/local/lib/node_modules/local-tld
> ./bin/local-tld-uninstall

+ sudo launchctl unload /Library/LaunchDaemons/ie.hood.local-tld-firewall.plist
launchctl: Couldn't stat("/Library/LaunchDaemons/ie.hood.local-tld-firewall.plist"): No such file or directory
nothing found to unload
npm WARN continuing anyway local-tld@3.0.2 preuninstall: `./bin/local-tld-uninstall`
npm WARN continuing anyway `sh "-c" "./bin/local-tld-uninstall"` failed with 1
npm ERR! error rolling back Error: EACCES, unlink '/usr/local/lib/node_modules/local-tld/.npmignore'
npm ERR! error rolling back  local-tld@3.0.2 { [Error: EACCES, unlink '/usr/local/lib/node_modules/local-tld/.npmignore']
npm ERR! error rolling back   errno: 3,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/local-tld/.npmignore' }
npm ERR! Error: EACCES, unlink '/usr/local/lib/node_modules/local-tld/.npmignore'
npm ERR!  { [Error: EACCES, unlink '/usr/local/lib/node_modules/local-tld/.npmignore']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/local-tld/.npmignore' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 11.4.2
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "local-tld"
npm ERR! cwd /Users/nitin
npm ERR! node -v v0.10.3
npm ERR! npm -v 1.2.17
npm ERR! path /usr/local/lib/node_modules/local-tld/.npmignore
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, unlink '/usr/local/lib/node_modules/local-tld/.npmignore'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/nitin/npm-debug.log
npm ERR! not ok code 0
[00:58][nitin@nitinmacbookpro:~]$ sudo npm install -g local-tld
npm http GET https://registry.npmjs.org/local-tld
npm http 304 https://registry.npmjs.org/local-tld

> local-tld@3.0.2 preuninstall /usr/local/lib/node_modules/local-tld
> ./bin/local-tld-uninstall

+ sudo launchctl unload /Library/LaunchDaemons/ie.hood.local-tld-firewall.plist

WARNING: Improper use of the sudo command could lead to data loss
or the deletion of important system files. Please double-check your
typing when using sudo. Type "man sudo" for more information.

To proceed, enter your password, or type Ctrl-C to abort.

Password:
Sorry, try again.
Password:
Sorry, try again.
Password:
sudo: 2 incorrect password attempts
```

actually I went to 3 more than once no difference
- npm install local-tld works

**Comment by jbolila** [comment]
I had an identical problem, that stopped happening when I went from the iTerm to Terminal, see [this](https://github.com/mxcl/homebrew/wiki/Common-Issues#launchctl-refuses-to-load-launchd-plist-files) from homebrew wiki.

**Comment by janl** [comment]
wow, that is crazy obscure!

**Comment by nborwankar** [comment]
I am using Terminal not iTerm all along.
Nitin

Nitin Borwankar nborwankar@gmail.com

**Comment by nborwankar** [comment]
Also the errorb shown on brew wiki doesn't apply to me. I have a sudo issue
not a socket issue.  The second potential cause in the wiki doesn't apply
eithe r.  Although the problemn does arise during launchctld invocation.
Sounds like a permissions issue in my case.

Nitin

Nitin Borwankar nborwankar@gmail.com

**Comment by bbn** [comment]
Exact same sudo problem for me. 
In case it's helpful, here's the npm install log: https://gist.github.com/bbn/5347136

**Comment by nborwankar** [comment]
Is this an OS Version issue?

Can Hoodie developers say on home page what OSX version including minor
version, this actually has been tested on.
Perhaps only Lion has been tested?  I am on Snow Leopard.
Also versions of Ruby, Nodejs, Homebrew.
Does it matter if one is using OpenDNS - does this interact badly with the
mdns implementation used to create local-tld?

Also just FYI - I have been using MacOSX for about 8 years now and I have
_never_ seen sudo behavior like this.
Not saying it's necessarily a hoodie issue but it could be a particular
combination of  some subset of launchctl version, nodejs version, OS
version and OpenDNS and ruby version interacting to produce this edge case.

Finally is it OK to install without the -g flag or is global install
somehow critical to Hoodie performance?

Nitin

---

Nitin Borwankar
nborwankar@gmail.com

**Comment by janl** [comment]
@bbn it looks like you are on Mountain Lion (Like I am), is that correct?

**Comment by janl** [comment]
> Is this an OS Version issue?

Maybe :)

> Can Hoodie developers say on home page what OSX version including minor
> version, this actually has been tested on. Perhaps only Lion has been tested?  I am on Snow Leopard.

I know we did have issues on a Snow Leopard once, but I believe we fixed them, but the developer moved to Mountain Lion now, and I haven’t checked back.

I have a Snow Leopard that I can try this with at some point, but capacity at this very moment, so for now, yes, assume Latest Mac OS X.

> Also versions of Ruby, Nodejs, Homebrew.

```
$ ruby -v
ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin12.0]
$ brew -v
Homebrew 0.9.4
$ node -v
v0.8.19
```

> Does it matter if one is using OpenDNS

Shouldn’t, but you never know, Mac OS X’s DNS resolution ways are dark and mysterious (and changing between versions a lot).

> - does this interact badly with the mdns implementation used to create local-tld?

There is no mdns in local-tld.

> Also just FYI - I have been using MacOSX for about 8 years now and I have
> _never_ seen sudo behavior like this.

10 years, same here.

> Finally is it OK to install without the -g flag or is global install somehow critical to Hoodie performance?

Functionality, not performance. The post-install script of hoodie needs sudo to set up a firewall route to make the magic work. You can manually disable the postinstall and do all the steps by hand, but we made it nice and bundeld for you so you don’t have to fiddle with it in the first place.

**Comment by janl** [comment]
@nborwankar silly question, but you don’t happen to run into having caps lock set for typing the password that one time or anything?

**Comment by bbn** [comment]
Yes - most recent OS.

**Comment by janl** [comment]
@bbn excellent, thanks, do you have any other oddities on your system that might help resolve this, because I literally have no fucking clue why this should happen, albeit I admit that what we are doing (`sudo` in an `npm postinstall` script is pretty dirty.

**Comment by janl** [comment]
I just pushed a commit (https://github.com/hoodiehq/local-tld/commit/e5c32331082c24d68039e91b1daaad55bdb12922) and version 3.0.3 to NPM that might solve this. Can you give it a shot?

Note that you are expected to run `npm install -g local-tld` not `sudo npm…` If you get permission errors, try starting from scratch by doing `sudo npm uninstall -g local-tld`.

**Comment by nborwankar** [comment]
OK - stupid me - I am on Mountain Lion , not Snow Leopard, those two word
wild cats confuse me :-)

Other versions

ruby -v
ruby 1.9.3p327 (2012-11-10 revision 37606) [x86_64-darwin11.4.2]
$ brew -v
Homebrew 0.9.4
$ node -v
v0.10.3

Nitin

---

Nitin Borwankar
nborwankar@gmail.com

**Comment by janl** [comment]
@nborwankar can you try the latest local-tld 3.0.3 I just pushed: https://github.com/hoodiehq/local-tld/issues/10#issuecomment-16145973

**Comment by nborwankar** [comment]
Will try again - BTW both those command lines with or without "sudo ..."
gave the same behavior eventually.
Also I've been away from the node dev world for about a year and ITMW the
idiom has changed from "don't use sudo with npm" to "use sudo with npm ".
So I have no f'in idea which one is the idiom du jour and in this kind of
situation I will try one then the other just for A/B purposes.
In this case A=B :-)
Nitin

---

Nitin Borwankar
nborwankar@gmail.com

**Comment by nborwankar** [comment]
OK so you want me to do an npm-install from inside the git repo, to get the
lates code right?

---

Nitin Borwankar
nborwankar@gmail.com

**Comment by janl** [comment]
On Apr 10, 2013, at 00:21 , Nitin Borwankar notifications@github.com wrote:

> Will try again - BTW both those command lines with or without "sudo ..." 
> gave the same behavior eventually. 
> Also I've been away from the node dev world for about a year and ITMW the 
> idiom has changed from "don't use sudo with npm" to "use sudo with npm ". 
> So I have no f'in idea which one is the idiom du jour and in this kind of 
> situation I will try one then the other just for A/B purposes. 
> In this case A=B :-) 

We are doing some crazy things, regardless of the mainline node doctrine :)

Jan

> Nitin 
> 
> ---
> 
> Nitin Borwankar 
> nborwankar@gmail.com 
>

**Comment by janl** [comment]
>  so you want me to do an npm-install from inside the git repo, to get the 
> lates code right?

Nope, it’s all on NPM already (<3 NPM).

Do this:

```
[sudo npm uninstall -g local-tld #optionsl]
npm install -g local-tld
```

(note that it wants to install local-tld version `3.0.3`.)

**Comment by janl** [comment]
(3.0.4 now, don’t mind me fixing)

**Comment by nborwankar** [comment]
Ha! Catch22!

$ sudo npm uninstall -g local-tld #optionsl
<hits same sudo loop! doesn't recognize my passwd>

I can just go rm -rf the local-tld dir in lib/node_modules and/or lib/node
Does the installer leave droppings anywhere else?

Nitin

---

Nitin Borwankar
nborwankar@gmail.com

**Comment by janl** [comment]
lolcopter :D

rm -rf the local-tld foler in your -g node_modules and manually run the contents of https://github.com/hoodiehq/local-tld/blob/master/bin/local-tld-uninstall

**Comment by nborwankar** [comment]
Jan,

So what was the issue you fixed?

I did the local uninstall and worked like a charm.

18:22][nitin@nitinmacbookpro:~/git/local-tld/bin(master)]$
./local-tld-uninstall
- sudo launchctl unload
  /Library/LaunchDaemons/ie.hood.local-tld-firewall.plist
- launchctl unload
  /Users/nitin/Library/LaunchAgents/ie.hood.local-tld-service.plist
- sudo rm -f /Library/LaunchDaemons/ie.hood.local-tld-firewall.plist
- rm -f /Users/nitin/Library/LaunchAgents/ie.hood.local-tld-service.plist
- sudo rm -f /etc/resolver/dev

Then so did the next steps, although there were a couple of OCD'ish
complaints about nonexistent readme's and 'speling'
from npm about dependent packages.

[18:19][nitin@nitinmacbookpro:~]$ npm install -g local-tld
npm http GET https://registry.npmjs.org/local-tld
npm http 200 https://registry.npmjs.org/local-tld
npm http GET https://registry.npmjs.org/local-tld/-/local-tld-3.0.4.tgz
npm http 200 https://registry.npmjs.org/local-tld/-/local-tld-3.0.4.tgz
npm http GET
https://github.com/sstephenson/dnsserver.js/archive/library.tar.gz
npm http GET https://registry.npmjs.org/http-proxy
npm http GET https://registry.npmjs.org/watchfd
npm http 304 https://registry.npmjs.org/watchfd
npm http 304 https://registry.npmjs.org/http-proxy
npm http 200
https://github.com/sstephenson/dnsserver.js/archive/library.tar.gz
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/pkginfo
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/colors
npm http 304 https://registry.npmjs.org/pkginfo
npm http GET https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/wordwrap

> local-tld@3.0.4 postinstall /usr/local/lib/node_modules/local-tld
> ./bin/local-tld-setup

++ pwd
- PWD=/usr/local/lib/node_modules/local-tld
  ++ dirname ./bin/local-tld-setup
- MY_PATH=./bin
  ++ cd ./bin
  ++ pwd
- MY_PATH=/usr/local/lib/node_modules/local-tld/bin
- ETC=/usr/local/lib/node_modules/local-tld/bin/../etc
  ++ npm root -g
- NODE_ROOT=/usr/local/lib/node_modules
- sed -e 's,{{NODE_ROOT}},/usr/local/lib/node_modules,'
  /usr/local/lib/node_modules/local-tld/bin/../etc/ie.hood.local-tld-service.plist.tpl
- sudo mkdir -p /etc/resolver
- sudo cp /usr/local/lib/node_modules/local-tld/bin/../etc/resolver.dev
  /etc/resolver/dev
- sudo cp
  /usr/local/lib/node_modules/local-tld/bin/../etc/ie.hood.local-tld-firewall.plist
  /Library/LaunchDaemons/
- cp
  /usr/local/lib/node_modules/local-tld/bin/../etc/ie.hood.local-tld-service.plist
  /Users/nitin/Library/LaunchAgents/
- sudo launchctl load -Fw
  /Library/LaunchDaemons/ie.hood.local-tld-firewall.plist
  ie.hood.local-tld-firewall: Already loaded
- launchctl unload
  /Users/nitin/Library/LaunchAgents/ie.hood.local-tld-service.plist
- launchctl load -Fw
  /Users/nitin/Library/LaunchAgents/ie.hood.local-tld-service.plist
- echo 'Setup done.'
  Setup done.
  npm WARN package.json assert@0.4.9 No README.md file found!
  npm WARN package.json jsdom-jquery-example@0.2.0 No README.md file found!
  npm WARN package.json path@0.4.9 No README.md file found!
  npm WARN package.json url@0.4.9 No README.md file found!
  npm WARN package.json util@0.4.9 No README.md file found!
  npm WARN package.json mustache@0.3.1-dev No README.md file found!
  npm WARN package.json connect@1.6.4 No README.md file found!
  npm WARN package.json cssom@0.2.2 No README.md file found!
  npm WARN package.json connect@1.7.1 No README.md file found!
  npm WARN package.json jquery@1.6.3 No README.md file found!
  npm WARN package.json events.node@0.4.9 No README.md file found!
  npm WARN package.json connect@1.6.0 No README.md file found!
  npm WARN package.json eventemitter2@0.4.1 'contributers' should probably be
  'contributors'
  local-tld@3.0.4 /usr/local/lib/node_modules/local-tld
  ├── dnsserver@0.1.0
  ├── watchfd@0.0.9
  └── http-proxy@0.8.7 (colors@0.6.0-1, pkginfo@0.2.3, optimist@0.3.7)
  [18:20][nitin@nitinmacbookpro:~]$

Onward!

---

Nitin Borwankar
nborwankar@gmail.com

**Comment by nborwankar** [comment]
So after the rest of the install which worked without errors, I created a
hoodie app and am getting other errors.  That's a separate issue so I'll
open a different one.
This one is now "works for me" :-)

---

Nitin Borwankar
nborwankar@gmail.com

**Comment by pagameba** [comment]
The reason this is breaking is because you are running npm with sudo and within the postinstall script it is running sudo on some embedded commands.  The context for sudo in the postinstall script is then incorrect and matches no known user so no password will match.  I think that it should incorporate something like this:

if [ `id -u` -eq 0 ]
then
    mkdir -p /etc/resolver
    cp $ETC/resolver.dev /etc/resolver/dev
    cp $ETC/ie.hood.local-tld-firewall.plist /Library/LaunchDaemons/
    cp $ETC/ie.hood.local-tld-service.plist $HOME/Library/LaunchAgents/
    launchctl load -Fw /Library/LaunchDaemons/ie.hood.local-tld-firewall.plist
else
    sudo mkdir -p /etc/resolver
    sudo cp $ETC/resolver.dev /etc/resolver/dev
    sudo cp $ETC/ie.hood.local-tld-firewall.plist /Library/LaunchDaemons/
    cp $ETC/ie.hood.local-tld-service.plist $HOME/Library/LaunchAgents/
    sudo launchctl load -Fw /Library/LaunchDaemons/ie.hood.local-tld-firewall.plist
fi

but I'm not a bash expert.  Once you've used sudo npm install -g local-tld everything is all messed up and you can't properly uninstall or reinstall without manually removing the package from /usr/local/lib/node_modules/local-tld or fixing the permissions.

**Comment by bbn** [comment]
got it to work by manually wiping the install, changing the perms on my global module folder, then reinstalling without sudo.

not ideal - recommend perhaps rethinking whether this component is necessary for hood.ie

**Comment by janl** [comment]
local-tld is definitely part of the whole hoodie experience, there is no question. But given it’s brittle nature an trouble porting it to other systems with verbatim functionality makes me ponder making this an optional add-on for mac folks.

Before going there thought, I’d like to try and hammer out the kinks to see if it can be done :)

**Comment by janl** [comment]
@pagameba thanks, I committed 26870b4 which does just that, thanks :)

**Comment by pagameba** [comment]
you are welcome!  I came across local-tld through a link to hood.ie, which sounds awesome.  I wanted to try local-tld and ran into some difficulty so I was checking the issues and thought I might be able to lend some insight on this issue, glad it was of use :)  Sadly I couldn't get local-tld to do anything and I ran out of time to troubleshoot it further.

**Comment by cupofjoakim** [comment]
I'm also having difficulties. Being given the typical sudo-loop just as @nborwankar. I erased everything and tried 'npm install -g local-tld' without sudo, here's the error: 

npm ERR! Error: EACCES, open '/Users/joakim/.npm/8993e262-local-tld.lock'
npm ERR!  { [Error: EACCES, open '/Users/joakim/.npm/8993e262-local-tld.lock']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/Users/joakim/.npm/8993e262-local-tld.lock' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 12.3.0
npm ERR! command "/usr/local/Cellar/node/0.10.3/bin/node" "/usr/local/bin/npm" "install" "-g" "local-tld"
npm ERR! cwd /Users/joakim
npm ERR! node -v v0.10.3
npm ERR! npm -v 1.2.17
npm ERR! path /Users/joakim/.npm/8993e262-local-tld.lock
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, open '/Users/joakim/.npm/8993e262-local-tld.lock'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/joakim/npm-debug.log
npm ERR! not ok code 0

I'm also running mountain lion, btw.

**Comment by pagameba** [comment]
If you previously ran the command with sudo then there are likely some root-owned files left around, try deleting the lock file at /Users/joakim/.npm/8993e262-local-tld.lock manually and running it again.

**Comment by cupofjoakim** [comment]
It kind of puzzles me, but /Users/joakim/.npm/8993e262-local-tld.lock doesn't exist.

**Comment by pagameba** [comment]
what about permissions on /Users/joakim/.npm, is it writable by your user?

**Comment by janl** [comment]
I pushed a bunch of updates that should fix this. The problem is that you now have old artefacts that don't have the fixes.

Try this:

sudo rm -rf /path/to/global/node_modules
sudo chmod -R $USER /path/to/global/node_modules
npm install local-tld

**Comment by cupofjoakim** [comment]
It wasn't, so I changed it and now I recieved a new error:

npm http GET https://registry.npmjs.org/local-tld
npm http 304 https://registry.npmjs.org/local-tld
npm http GET https://registry.npmjs.org/local-tld/-/local-tld-3.0.5.tgz
npm http 200 https://registry.npmjs.org/local-tld/-/local-tld-3.0.5.tgz
npm ERR! Error: EPERM, chown '/Users/joakim/.npm/local-tld/3.0.5/package.tgz'
npm ERR!  { [Error: EPERM, chown '/Users/joakim/.npm/local-tld/3.0.5/package.tgz']
npm ERR!   errno: 50,
npm ERR!   code: 'EPERM',
npm ERR!   path: '/Users/joakim/.npm/local-tld/3.0.5/package.tgz' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 12.3.0
npm ERR! command "/usr/local/Cellar/node/0.10.3/bin/node" "/usr/local/bin/npm" "install" "-g" "local-tld"
npm ERR! cwd /Users/joakim
npm ERR! node -v v0.10.3
npm ERR! npm -v 1.2.17
npm ERR! path /Users/joakim/.npm/local-tld/3.0.5/package.tgz
npm ERR! code EPERM
npm ERR! errno 50
npm ERR! stack Error: EPERM, chown '/Users/joakim/.npm/local-tld/3.0.5/package.tgz'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/jokkegoestasty/npm-debug.log
npm ERR! not ok code 0

Should I post the contents of npm-debug? 

EDIT: Going to try @janl's suggestion, hang on a minute

**Comment by isaacs** [comment]
`sudo npm cache clean -f`

**Comment by janl** [comment]
Not sure, it looks like your NPM install is a bit hosed. Try making sure all paths belong to your current user.

**Comment by cupofjoakim** [comment]
Okay, so now I've cleansed my system from node (followed guide for node to make sure everything was gone), together with all the downloaded files, reinstalled them both, but still an error. 

npm http GET https://registry.npmjs.org/local-tld
npm http 304 https://registry.npmjs.org/local-tld
npm http GET https://registry.npmjs.org/local-tld/-/local-tld-3.0.5.tgz
npm http 200 https://registry.npmjs.org/local-tld/-/local-tld-3.0.5.tgz
npm ERR! Error: EPERM, chown '/Users/joakim/.npm/local-tld/3.0.5/package.tgz'
npm ERR!  { [Error: EPERM, chown '/Users/joakim/.npm/local-tld/3.0.5/package.tgz']
npm ERR!   errno: 50,
npm ERR!   code: 'EPERM',
npm ERR!   path: '/Users/joakim/.npm/local-tld/3.0.5/package.tgz' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 12.3.0
npm ERR! command "/usr/local/Cellar/node/0.10.3/bin/node" "/usr/local/bin/npm" "install" "-g" "local-tld"
npm ERR! cwd /usr/local/Library
npm ERR! node -v v0.10.3
npm ERR! npm -v 1.2.17
npm ERR! path /Users/joakim/.npm/local-tld/3.0.5/package.tgz
npm ERR! code EPERM
npm ERR! errno 50
npm ERR! stack Error: EPERM, chown '/Users/joakim/.npm/local-tld/3.0.5/package.tgz'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/Library/npm-debug.log
npm ERR! not ok code 0

Fun thing is: I'm one of those front-enders who knows basically nothing about using the terminal. I'm learning loads here. I don't have any idea about how to make "all paths belong to my current user" though.

**Comment by janl** [comment]
Sorry this is giving you so much trouble!

> npm ERR! Error: EPERM, chown '/Users/joakim/.npm/local-tld/3.0.5/package.tgz'

This means that the path `/Users/joakim/.npm/local-tld/3.0.5` isn’t accessible to the current user. This is likely a permission issue in you `~/.npm/` path.

Can you try running this:

```
sudo chmod -R $USER ~/.npm
```

(assuming you are the user `joakim`) and then try

```
npm install -g local-tld
```

again?

Note: _no_ `sudo`

**Comment by cupofjoakim** [comment]
I'm getting
   chmod: Invalid file mode: joakim
on the first command.

**Comment by janl** [comment]
Eh, sorry, brainfart on my end. The command is:

```
sudo chown -R $USER ~/.npm
```

**Comment by cupofjoakim** [comment]
Hey, it worked! Thanks @janl!

**Comment by janl** [comment]
Wootwoot. Closing this one.

**Comment by donaldpipowitch** [comment]
Run into the same issue which was very annoying :(

I run 3.0.5 with sudo first even if the commit message "Protect against people accidentally using `sudo npm install`." says this shouldn't be possible? After that I searched in the wrong repo for help (hoodiehq/local-tld-lib) and somewhere in the middle of fixing this with the terminal prompts I had to reinstall node... Now everything works, but it consumed a lot of time and I can't see (yet) why local-tld isn't optional if you just want to test hoodie...?

**Comment by bbn** [comment]
+1 
An unnecessary complication for hood.ie, and preventing the framework from being used by a lot of people.

**Comment by janl** [comment]
It is early days and I understand your frustration with issues around Hoodie, but these are inevitable and the entire team is incredibly grateful for you giving Hoodie a spin and take the time to report issues that we then can fix and make the Hoodie better and better.

I very much disagree though that this is unnecessary. I agree that Hoodie should work without local-tld and we are getting close to have that ready. 

Local-tld makes the entire Hoodie experience so much nicer, that I consider it essential.

Please let us know if there are any existing issues. To my knowledge the latest version of local-tld works fine.

<3
Jan

**Comment by nborwankar** [comment]
Hi Jan,

This deserves a separate discussion but can you lay out in bullet points
what you consider to be the essence of "the Hoodie experience".  I gather
that the major goal is making it drop dead simple to create apps that have
local-data-synced-with-cloud.
Now with respect to this goal is local-tld a "must-have" or
"really-really-really-nice-to-have".  I think you're saying it's the latter.
In which case why not proceed in steps - at least get it working as a
 baseline during the install. Take a check point and say now we add
local-tld and even if you can't we still can do .......

If we lay out bullet points then we can draw a line which separates the
must-haves from the others - right now it's not clear to the rest of us
what the different benefits are vs the pain.

Do we have a hoodie-discuss on google groups to take this further?

Nitin

---

Nitin Borwankar
nborwankar@gmail.com

**Comment by janl** [comment]
Not sure what needs discussing other than actual issues with the software.

Please report of anything does not work for you.

**Comment by bbn** [comment]
Well, for one thing, local-tld clobbers all of the local DNS I already have set up on my machine.

**Comment by janl** [comment]
Please define "local DNS".

**Comment by bbn** [comment]
It's ok. If you are going to update hood.ie so that I can use it without local-tld, I can wait for that.

**Comment by janl** [comment]
I would still like to understand what exactly the issue is, so we can fix it or document it as a limitation :)

**Comment by nborwankar** [comment]
The issue is that if an install fails - the files are left in an unknown
state which is very hard to revert to "last known good".
It would be very very useful to have a clean uninstall script that removes
crud left by hoodie specific installation as well as dependencies via "brew
install couchdb" and "brew install nodejs".  As we speak I have a "couldn't
link erlang" error from brew install couchdb.  It requires repeated
attempts ( about 30+ and counting ) to "brew link erlang" read what file
fails to link, then manually delete the file. Repeat till you remove
everything and link succeeds.  Given the number of files erlang installs
this can go on for awhile. "brew uninstall erlang" doesn't cleanup well
enough.

here's a fraction of my session

[...]

Error: Could not symlink file: /usr/local/Cellar/erlang/R15B03-1/bin/epmd
/usr/local/bin/epmd may already exist.
/usr/local/bin may not be writable.
[08:34][nitin@nitinmacbookpro:/Volumes/HybridSeagate/my/code/git]$ sudo rm
/usr/local/bin/epmd; brew link erlang
Linking /usr/local/Cellar/erlang/R15B03-1... Warning: Could not link
erlang. Unlinking...

Error: Could not symlink file:
/usr/local/Cellar/erlang/R15B03-1/bin/dialyzer
/usr/local/bin/dialyzer may already exist.
/usr/local/bin may not be writable.
[08:35][nitin@nitinmacbookpro:/Volumes/HybridSeagate/my/code/git]$ sudo rm
/usr/local/bin/dialyzer; brew link erlang
Linking /usr/local/Cellar/erlang/R15B03-1... Warning: Could not link
erlang. Unlinking...

Error: Could not symlink file:
/usr/local/Cellar/erlang/R15B03-1/share/man/man7/STANDARD-MIB.7
/usr/local/share/man/man7/STANDARD-MIB.7 may already exist.
/usr/local/share/man/man7 may not be writable.
[08:35][nitin@nitinmacbookpro:/Volumes/HybridSeagate/my/code/git]$ sudo rm
/usr/local/share/man/man7/STANDARD-MIB.7; brew link erlang
Linking /usr/local/Cellar/erlang/R15B03-1... Warning: Could not link
erlang. Unlinking...

Error: Could not symlink file:
/usr/local/Cellar/erlang/R15B03-1/share/man/man7/SNMPv2-TM.7
/usr/local/share/man/man7/SNMPv2-TM.7 may already exist.
/usr/local/share/man/man7 may not be writable.
[08:36][nitin@nitinmacbookpro:/Volumes/HybridSeagate/my/code/git]$ sudo rm
/usr/local/share/man/man7/SNMP; brew link erlang
SNMP-COMMUNITY-MIB.7       SNMP-MPD-MIB.7             SNMP-TARGET-MIB.7
     SNMP-USM-AES-MIB.7         SNMPv2-MIB.7
SNMP-FRAMEWORK-MIB.7       SNMP-NOTIFICATION-MIB.7
 SNMP-USER-BASED-SM-MIB.7   SNMP-VIEW-BASED-ACM-MIB.7  SNMPv2-TM.7

[08:36][nitin@nitinmacbookpro:/Volumes/HybridSeagate/my/code/git]$ sudo rm
/usr/local/share/man/man7/SNMP*; brew link erlang
Linking /usr/local/Cellar/erlang/R15B03-1... Warning: Could not link
erlang. Unlinking...

Error: Could not symlink file:
/usr/local/Cellar/erlang/R15B03-1/share/man/man7/RFC1213-MIB.7
/usr/local/share/man/man7/RFC1213-MIB.7 may already exist.
/usr/local/share/man/man7 may not be writable.
[08:36][nitin@nitinmacbookpro:/Volumes/HybridSeagate/my/code/git]$ sudo rm
/usr/local/share/man/man7/RFC1213-MIB.7; brew link erlang
Linking /usr/local/Cellar/erlang/R15B03-1... Warning: Could not link
erlang. Unlinking...

Error: Could not symlink file:
/usr/local/Cellar/erlang/R15B03-1/share/man/man7/OTP-SNMPEA-MIB.7
/usr/local/share/man/man7/OTP-SNMPEA-MIB.7 may already exist.
/usr/local/share/man/man7 may not be writable.
[08:37][nitin@nitinmacbookpro:/Volumes/HybridSeagate/my/code/git]$ sudo rm
/usr/local/share/man/man7/OTP-SNMPEA-MIB.7; brew link erlang
Linking /usr/local/Cellar/erlang/R15B03-1... Warning: Could not link
erlang. Unlinking...

Error: Could not symlink file:
/usr/local/Cellar/erlang/R15B03-1/share/man/man7/INET-ADDRESS-MIB.7
/usr/local/share/man/man7/INET-ADDRESS-MIB.7 may already exist.
/usr/local/share/man/man7 may not be writable.
[08:37][nitin@nitinmacbookpro:/Volumes/HybridSeagate/my/code/git]$ sudo rm
/usr/local/share/man/man7/; brew link erlang
rm: /usr/local/share/man/man7/: is a directory
iLinking /usr/local/Cellar/erlang/R15B03-1... Warning: Could not link
erlang. Unlinking...
^C

[08:38][nitin@nitinmacbookpro:/Volumes/HybridSeagate/my/code/git]$ sudo rm
/usr/local/share/man/man7/INET-ADDRESS-MIB.7; brew link erlang
Linking /usr/local/Cellar/erlang/R15B03-1... Warning: Could not link
erlang. Unlinking...

[...] and so on.

I know it's not your fault but it sure blocks an install of hoodie once an
install fails.
An "install distclean" equivalent would help.

---

Nitin Borwankar
nborwankar@gmail.com

**Comment by bbn** [comment]
"brew install couchdb" not working for me either -- issue here is that it can't find the file to download. I noticed that the recipe was looking for 1.2.0, and I edited it locally to look for 1.3.0 - same same. 

I _do_ have couchdb on my machine (installed from the OS X installer) but hood.ie seems to require the command-line version to be present.

It might be worth mentioning that I would have reported this problem earlier, but I wasn't sure which of the many git repos is the right place to report this type of thing! Perhaps the hood.ie site repo?

Anywho. Very interested in the potential of hood.ie, and I understand wanting to make the experience as consistent as possible (convention over configuration or whatever). But those are lofty goals and right now I'd just like to kick the tires! :)

**Comment by nborwankar** [comment]
It would be good to know if anyone outside the core team has got hoodie
running and how they dealt with these issues.

---

Nitin Borwankar
nborwankar@gmail.com

**Comment by janl** [comment]
On Apr 16, 2013, at 18:21 , Nitin Borwankar notifications@github.com wrote:

> It would be good to know if anyone outside the core team has got hoodie 
> running and how they dealt with these issues. 

I know plenty of people who run this without issues.

> ---
> 
> Nitin Borwankar 
> nborwankar@gmail.com 
>

**Comment by janl** [comment]
On Apr 16, 2013, at 17:56 , Nitin Borwankar notifications@github.com wrote:

> The issue is that if an install fails - the files are left in an unknown 
> state which is very hard to revert to "last known good". 

This is no longer true with the 3.0.8 release of local-tld. The issues you
describe have nothing to do with hoodie.

> It would be very very useful to have a clean uninstall script that removes 
> crud left by hoodie specific installation as well as dependencies via "brew 
> install couchdb" and "brew install nodejs". As we speak I have a "couldn't 
> link erlang" error from brew install couchdb. It requires repeated 
> attempts ( about 30+ and counting ) to "brew link erlang" read what file 
> fails to link, then manually delete the file. Repeat till you remove 
> everything and link succeeds. Given the number of files erlang installs 
> this can go on for awhile. "brew uninstall erlang" doesn't cleanup well 
> enough. 
> 
> here's a fraction of my session 
> 
> [...] 
> 
> Error: Could not symlink file: /usr/local/Cellar/erlang/R15B03-1/bin/epmd 
> /usr/local/bin/epmd may already exist. 
> /usr/local/bin may not be writable. 
> [08:34][nitin@nitinmacbookpro:/Volumes/HybridSeagate/my/code/git]$ sudo rm 
> /usr/local/bin/epmd; brew link erlang 
> Linking /usr/local/Cellar/erlang/R15B03-1... Warning: Could not link 
> erlang. Unlinking... 
> 
> Error: Could not symlink file: 
> /usr/local/Cellar/erlang/R15B03-1/bin/dialyzer 
> /usr/local/bin/dialyzer may already exist. 
> /usr/local/bin may not be writable. 
> [08:35][nitin@nitinmacbookpro:/Volumes/HybridSeagate/my/code/git]$ sudo rm 
> /usr/local/bin/dialyzer; brew link erlang 
> Linking /usr/local/Cellar/erlang/R15B03-1... Warning: Could not link 
> erlang. Unlinking... 
> 
> Error: Could not symlink file: 
> /usr/local/Cellar/erlang/R15B03-1/share/man/man7/STANDARD-MIB.7 
> /usr/local/share/man/man7/STANDARD-MIB.7 may already exist. 
> /usr/local/share/man/man7 may not be writable. 
> [08:35][nitin@nitinmacbookpro:/Volumes/HybridSeagate/my/code/git]$ sudo rm 
> /usr/local/share/man/man7/STANDARD-MIB.7; brew link erlang 
> Linking /usr/local/Cellar/erlang/R15B03-1... Warning: Could not link 
> erlang. Unlinking... 
> 
> Error: Could not symlink file: 
> /usr/local/Cellar/erlang/R15B03-1/share/man/man7/SNMPv2-TM.7 
> /usr/local/share/man/man7/SNMPv2-TM.7 may already exist. 
> /usr/local/share/man/man7 may not be writable. 
> [08:36][nitin@nitinmacbookpro:/Volumes/HybridSeagate/my/code/git]$ sudo rm 
> /usr/local/share/man/man7/SNMP; brew link erlang 
> SNMP-COMMUNITY-MIB.7 SNMP-MPD-MIB.7 SNMP-TARGET-MIB.7 
> SNMP-USM-AES-MIB.7 SNMPv2-MIB.7 
> SNMP-FRAMEWORK-MIB.7 SNMP-NOTIFICATION-MIB.7 
> SNMP-USER-BASED-SM-MIB.7 SNMP-VIEW-BASED-ACM-MIB.7 SNMPv2-TM.7 
> 
> [08:36][nitin@nitinmacbookpro:/Volumes/HybridSeagate/my/code/git]$ sudo rm 
> /usr/local/share/man/man7/SNMP*; brew link erlang 
> Linking /usr/local/Cellar/erlang/R15B03-1... Warning: Could not link 
> erlang. Unlinking... 
> 
> Error: Could not symlink file: 
> /usr/local/Cellar/erlang/R15B03-1/share/man/man7/RFC1213-MIB.7 
> /usr/local/share/man/man7/RFC1213-MIB.7 may already exist. 
> /usr/local/share/man/man7 may not be writable. 
> [08:36][nitin@nitinmacbookpro:/Volumes/HybridSeagate/my/code/git]$ sudo rm 
> /usr/local/share/man/man7/RFC1213-MIB.7; brew link erlang 
> Linking /usr/local/Cellar/erlang/R15B03-1... Warning: Could not link 
> erlang. Unlinking... 
> 
> Error: Could not symlink file: 
> /usr/local/Cellar/erlang/R15B03-1/share/man/man7/OTP-SNMPEA-MIB.7 
> /usr/local/share/man/man7/OTP-SNMPEA-MIB.7 may already exist. 
> /usr/local/share/man/man7 may not be writable. 
> [08:37][nitin@nitinmacbookpro:/Volumes/HybridSeagate/my/code/git]$ sudo rm 
> /usr/local/share/man/man7/OTP-SNMPEA-MIB.7; brew link erlang 
> Linking /usr/local/Cellar/erlang/R15B03-1... Warning: Could not link 
> erlang. Unlinking... 
> 
> Error: Could not symlink file: 
> /usr/local/Cellar/erlang/R15B03-1/share/man/man7/INET-ADDRESS-MIB.7 
> /usr/local/share/man/man7/INET-ADDRESS-MIB.7 may already exist. 
> /usr/local/share/man/man7 may not be writable. 
> [08:37][nitin@nitinmacbookpro:/Volumes/HybridSeagate/my/code/git]$ sudo rm 
> /usr/local/share/man/man7/; brew link erlang 
> rm: /usr/local/share/man/man7/: is a directory 
> iLinking /usr/local/Cellar/erlang/R15B03-1... Warning: Could not link 
> erlang. Unlinking... 
> ^C 
> 
> [08:38][nitin@nitinmacbookpro:/Volumes/HybridSeagate/my/code/git]$ sudo rm 
> /usr/local/share/man/man7/INET-ADDRESS-MIB.7; brew link erlang 
> Linking /usr/local/Cellar/erlang/R15B03-1... Warning: Could not link 
> erlang. Unlinking... 
> 
> [...] and so on. 
> 
> I know it's not your fault but it sure blocks an install of hoodie once an 
> install fails. 
> An "install distclean" equivalent would help. 
> 
> ---
> 
> Nitin Borwankar 
> nborwankar@gmail.com 
>

**Comment by nborwankar** [comment]
> The issues you describe have nothing to do with hoodie.
> I think saying "nothing to do ..." is rather strong.
> They come up while trying to install hoodie, as described on the install
> page.
> Having a separate couchdb installation, which I do have, doesn't seem
> enough, so that this particular installation method of couchdb is a
> requirement.   And that install process is rather brittle wrt failed or
> previous installs.

A workaround might be - suggest a way to use an existing couchdb.

In any case the current process has hit a wall for me.
I am going to give this a shot again in a while and see how it goes, as the
promise is great.
Thanks for the patience.

---

Nitin Borwankar
nborwankar@gmail.com

**Comment by janl** [comment]
On Apr 16, 2013, at 22:03 , Nitin Borwankar notifications@github.com wrote:

> > The issues you describe have nothing to do with hoodie. 
> > I think saying "nothing to do ..." is rather strong. 
> > They come up while trying to install hoodie, as described on the install 
> > page. 

Oh, I totally understand that we are responsible for the abstractions we
are using, but Hoodie does not have the power to break your Homebrew
installation, hence my phrasing.

> Having a separate couchdb installation, which I do have, doesn't seem 
> enough,

All Hoodie needs is a `couchdb` binary in your `PATH`.

> so that this particular installation method of couchdb is a 
> requirement. And that install process is rather brittle wrt failed or 
> previous installs. 

Yeah, it is early days, we keep hammering out the issues :)

> A workaround might be - suggest a way to use an existing couchdb. 

Skip the `brew install couchdb` step and make sure the `couchdb` binary
is in `PATH`.

> In any case the current process has hit a wall for me. 
> 
> I am going to give this a shot again in a while and see how it goes, as the 
> promise is great. 
> Thanks for the patience. 

Likewise, thanks for trying Hoodie :)

> ---
> 
> Nitin Borwankar 
> nborwankar@gmail.com 
>

**Comment by janl** [comment]
On Apr 16, 2013, at 18:10 , Ben Nevile notifications@github.com wrote:

> "brew install couchdb" not working for me either -- issue here is that it can't find the file to download. I noticed that the recipe was looking for 1.2.0, and I edited it locally to look for 1.3.0 - same same.

Can you post a log?

> I do have couchdb on my machine (installed from the OS X installer) but hood.ie seems to require the command-line version to be present.

Yeah, I have on the radar to make it work with the binary installer of CouchDB.

> It might be worth mentioning that I would have reported this problem earlier, but I wasn't sure which of the many git repos is the right place to report this type of thing! Perhaps the hood.ie site repo?

Sorry for the repo-flurry, feel free to open it where, we can redirect it to better places if they exist :)

> Anywho. Very interested in the potential of hood.ie, and I understand wanting to make the experience as consistent as possible (convention over configuration or whatever). But those are lofty goals and right now I'd just like to kick the tires! :)

Thanks for your patience!

**Comment by bbn** [comment]
Sure, here's a log:

```
bbn$ brew install couchdb
==> Downloading http://www.apache.org/dyn/closer.cgi?path=couchdb/releases/1.2.0/apache-couchdb-1.2.0.tar.gz
==> Best Mirror http://apache.mirror.iweb.ca/couchdb/releases/1.2.0/apache-couchdb-1.2.0.tar.gz

curl: (22) The requested URL returned error: 404
Error: Download failed: http://www.apache.org/dyn/closer.cgi?path=couchdb/releases/1.2.0/apache-couchdb-1.2.0.tar.gz
```

**Comment by janl** [comment]
OOOOOH, 1.2.0. That is an old release. You want to make sure your Homebrew is up to date: `brew update`

**Comment by bbn** [comment]
Hey that helped! Seems to be installing now (although it _did_ complain about my xcode version). Perhaps an infrequent problem, but I recommend adding "brew update" to the sequence of install instructions for those of us who don't use homebrew very often / ever.

**Comment by janl** [comment]
Lesson learned, will totally do, thanks!

The Xcode version is a warning that there is a newer version available, but as long as thing keep working you don’t necessarily have to upgrade.

**Comment by janl** [comment]
Fixed in https://github.com/hoodiehq/hood.ie/commit/8e1cf9be40dc98d8729e5a78ee071d5bec7790d6 and https://github.com/hoodiehq/my-first-hoodie/commit/6af8d448672d2a1c6ae4236e82e57b1d123b578f

**Comment by bbn** [comment]
huzzah! hoodie running in the browser, finally!

If I wanted to contribute a better error message for the missing couchdb case, what repo should I fork? 
Here's what the error looks like now:

```
smaller:abba bbn$ hoodie start

> abba@1.0.0 start /Users/bbn/mainsocial/hoodie/abba
> node node_modules/hoodie-app/lib/hoodie-app.js

Start local couch on port: 6008

/Users/bbn/mainsocial/hoodie/abba/node_modules/hoodie-app/node_modules/multicouch/node_modules/which/which.js:83
  throw new Error("not found: "+cmd)
        ^
Error: not found: couchdb
    at whichSync (/Users/bbn/mainsocial/hoodie/abba/node_modules/hoodie-app/node_modules/multicouch/node_modules/which/which.js:83:9)
    at new MultiCouch (/Users/bbn/mainsocial/hoodie/abba/node_modules/hoodie-app/node_modules/multicouch/lib/multicouch.js:21:40)
    at Object.<anonymous> (/Users/bbn/mainsocial/hoodie/abba/node_modules/hoodie-app/lib/hoodie-app.js:64:17)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
npm ERR! abba@1.0.0 start: `node node_modules/hoodie-app/lib/hoodie-app.js`
npm ERR! `sh "-c" "node node_modules/hoodie-app/lib/hoodie-app.js"` failed with 1
npm ERR! 
npm ERR! Failed at the abba@1.0.0 start script.
npm ERR! This is most likely a problem with the abba package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/hoodie-app/lib/hoodie-app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls abba
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 12.2.0
npm ERR! command "node" "/usr/local/bin/npm" "start"
npm ERR! cwd /Users/bbn/mainsocial/hoodie/abba
npm ERR! node -v v0.8.15
npm ERR! npm -v 1.1.66
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/bbn/mainsocial/hoodie/abba/npm-debug.log
npm ERR! not ok code 0
```

**Comment by bbn** [comment]
PS. even after updating homebrew, the couch version installed was 1.2.1, not 1.3.0. Not sure if that's what you would expect.

**Comment by janl** [comment]
I believe @caolan's fork already does this better. It is due to land later this week.

**Comment by janl** [comment]
1.2.1 is fine. 

There are reasons 1.3.0 isn't in Homebrew yet that are beyond the scope of Hoodie.

**Comment by iheanyi** [comment]
Sorry to re-open this, but I'm encountering the same issue with local-tld.
Here's the log

```
847 info postuninstall local-tld@4.0.0
848 error local-tld@4.0.0 postinstall: `./bin/local-tld-setup`
848 error Exit status 64
849 error Failed at the local-tld@4.0.0 postinstall script.
849 error This is most likely a problem with the local-tld package,
849 error not with npm itself.
849 error Tell the author that this fails on your system:
849 error     ./bin/local-tld-setup
849 error You can get their info via:
849 error     npm owner ls local-tld
849 error There is likely additional logging output above.
850 error System Darwin 13.1.0
851 error command "node" "/usr/local/bin/npm" "install" "-g" "local-tld"
852 error cwd /Volumes/Storage Drive/Users/iheanyi
853 error node -v v0.10.28
854 error npm -v 1.4.9
855 error code ELIFECYCLE
856 verbose exit [ 1, true ]
```

**Comment by janl** [comment]
local-tld can’t be installed when running under sudo. Try this:

``` shell
sudo rm -rf /usr/local/lib/node_modules/local-tld
sudo chown -R $USER /usr/local/lib/node_modules/
npm install -g local-tld
```

**Comment by iheanyi** [comment]
Hm, weird. That finally fixed it, though I tried it before. Thanks @janl!
